name: Build & Deploy to EdgeOne

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y xz-utils
          sudo apt install -y fonts-noto fonts-noto-cjk fonts-noto-color-emoji
          sudo fc-cache -fv
      
      - name: Setup Typst
        uses: typst-community/setup-typst@v4
      
      - name: Setup UV
        uses: astral-sh/setup-uv@v7
    
      - name: Run Build Script
        run: |
          uv run build.py build -f

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "_site"
      
      - name: Deploy to EdgeOne
        run: |
          # 使用官方 CLI 部署 _site 目录
          npx edgeone pages deploy ./_site -n myblog -t ${{ secrets.EDGEONE_API_TOKEN }} -e production
        env:
          # 从仓库密钥中读取 Token
          EDGEONE_API_TOKEN: ${{ secrets.EDGEONE_API_TOKEN }}
