name: Build & Deploy to EdgeOne

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y xz-utils
          sudo apt install -y fonts-noto fonts-noto-cjk fonts-noto-color-emoji
          sudo fc-cache -fv
      
      - name: Setup Typst
        uses: typst-community/setup-typst@v4
      
      - name: Setup UV
        uses: astral-sh/setup-uv@v7
    
      - name: Run Build Script
        run: |
          uv run build.py build -f
      
      - name: Deploy to EdgeOne
        run: |
          # 使用官方 CLI 部署 _site 目录
          npx edgeone pages deploy ./_site -n myblog -t ${{ secrets.EDGEONE_API_TOKEN }} -e production
        env:
          # 从仓库密钥中读取 Token
          EDGEONE_API_TOKEN: ${{ secrets.EDGEONE_API_TOKEN }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: myblog
          directory: ./
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: main
          # Optional: Change the working directory
          # All my website content is in the site folder
          workingDirectory: ./_site
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerVersion: '3'
